-- Migration v5: Realtime for admin + submission rate limit
-- Run in Supabase SQL Editor AFTER migration_v4

-- Realtime: live updates in moderator panel
do $$
begin
  alter publication supabase_realtime add table public.incidents;
exception
  when duplicate_object then null;
end $$;

-- Rolling rate log (new submissions only)
create table if not exists public.submission_rate_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

create index if not exists submission_rate_log_created_at_idx
  on public.submission_rate_log (created_at desc);

-- Internal rate-limit log: no client access (submit_incident is security definer).
alter table public.submission_rate_log enable row level security;
-- Intentionally no policies — anon/authenticated cannot read or write this table.

-- Patch submit_incident: max 40 new reports / hour (re-reports unaffected)
create or replace function submit_incident(
  p_artist text,
  p_report_type text,
  p_title text,
  p_quote text,
  p_platform text,
  p_post_author text,
  p_post_date date,
  p_screenshot_date date,
  p_url text,
  p_lang text,
  p_screenshot_urls text[] default '{}',
  p_hp text default ''
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_platform text;
  v_new_count integer;
  v_recent integer;
begin
  if p_hp is not null and p_hp <> '' then
    return;
  end if;

  v_platform := normalize_platform(p_platform);

  update incidents
    set report_count     = report_count + 1,
        last_reported_at = now(),
        quote            = case
          when p_quote is not null and length(trim(p_quote)) > length(trim(quote))
            then p_quote
          else quote
        end,
        artist           = coalesce(nullif(trim(p_artist), ''), artist),
        report_type      = coalesce(nullif(trim(p_report_type), ''), report_type),
        title            = coalesce(nullif(trim(p_title), ''), title),
        platform         = v_platform,
        post_author      = coalesce(nullif(trim(p_post_author), ''), post_author),
        post_date        = coalesce(p_post_date, post_date),
        screenshot_date  = coalesce(p_screenshot_date, screenshot_date),
        screenshot_urls  = case
          when p_screenshot_urls is not null and array_length(p_screenshot_urls, 1) > 0
            then screenshot_urls || p_screenshot_urls
          else screenshot_urls
        end
    where url = p_url
    returning id, report_count into v_id, v_new_count;

  if found then
    insert into incident_events (incident_id, event_type, payload, actor)
    values (
      v_id,
      're_report',
      jsonb_build_object('report_count', v_new_count),
      'reporter'
    );
    return;
  end if;

  select count(*)::integer into v_recent
  from submission_rate_log
  where created_at > now() - interval '1 hour';

  if v_recent >= 40 then
    return;
  end if;

  insert into incidents (
    artist, report_type, title, quote, platform,
    post_author, post_date, screenshot_date, screenshot_urls,
    url, lang, status, priority, report_count, last_reported_at
  ) values (
    p_artist, p_report_type, p_title, p_quote, v_platform,
    p_post_author, p_post_date, p_screenshot_date,
    coalesce(p_screenshot_urls, '{}'),
    p_url, p_lang, 'new', 'medium', 1, now()
  )
  returning id into v_id;

  insert into submission_rate_log default values;

  insert into incident_events (incident_id, event_type, payload, actor)
  values (
    v_id,
    'submitted',
    jsonb_build_object(
      'report_type', p_report_type,
      'platform', v_platform,
      'artist', p_artist
    ),
    'reporter'
  );
end;
$$;

grant execute on function submit_incident to anon, authenticated;
