-- Migration v4: rejected/duplicate statuses, internal_note, incident_events, submit_incident fixes
-- Run in Supabase Dashboard → SQL Editor AFTER schema.sql + migration_v2 + migration_v3

-- ── Platform normalizer ──────────────────────────────────────────────
create or replace function normalize_platform(p text)
returns text
language sql
immutable
as $$
  select case
    when p is null or trim(p) = '' then 'Other'
    when lower(replace(replace(p, ' ', ''), '(', '')) like '%xtwitter%'
      or lower(p) in ('x', 'twitter') then 'X (Twitter)'
    when lower(p) like '%instagram%' then 'Instagram'
    when lower(p) like '%tiktok%' then 'TikTok'
    when lower(p) like '%youtube%' then 'YouTube'
    when lower(p) like '%facebook%' then 'Facebook'
    when lower(p) like '%threads%' then 'Threads'
    else p
  end;
$$;

-- Normalize existing rows
update incidents set platform = normalize_platform(platform);

-- ── Statuses: add rejected + duplicate ───────────────────────────────
alter table incidents drop constraint if exists incidents_status_check;
alter table incidents add constraint incidents_status_check
  check (status in (
    'new', 'under_review', 'needs_evidence', 'verified',
    'ready_for_submission', 'rejected', 'duplicate', 'archived'
  ));

update incidents set status = 'rejected' where status = 'archived';

-- ── Internal note (moderator-only, stored in DB) ─────────────────────
alter table incidents add column if not exists internal_note text;

-- ── Activity log ─────────────────────────────────────────────────────
create table if not exists incident_events (
  id bigint generated by default as identity primary key,
  incident_id bigint not null references incidents(id) on delete cascade,
  event_type text not null check (event_type in (
    'submitted', 're_report', 'status_changed', 'note_updated'
  )),
  payload jsonb not null default '{}'::jsonb,
  actor text not null default 'system',
  created_at timestamptz not null default now()
);

create index if not exists incident_events_incident_id_idx
  on incident_events (incident_id, created_at desc);

alter table incident_events enable row level security;

drop policy if exists "Authenticated can select events" on incident_events;
create policy "Authenticated can select events" on incident_events
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can insert events" on incident_events;
create policy "Authenticated can insert events" on incident_events
  for insert with check (auth.role() = 'authenticated');

-- Backfill: one submitted event per existing incident
insert into incident_events (incident_id, event_type, payload, actor, created_at)
select
  id,
  'submitted',
  jsonb_build_object('report_type', report_type, 'platform', platform),
  'reporter',
  created_at
from incidents i
where not exists (
  select 1 from incident_events e
  where e.incident_id = i.id and e.event_type = 'submitted'
);

-- ── submit_incident: normalize platform, refresh data on re-report, log events ──
create or replace function submit_incident(
  p_artist text,
  p_report_type text,
  p_title text,
  p_quote text,
  p_platform text,
  p_post_author text,
  p_post_date date,
  p_screenshot_date date,
  p_url text,
  p_lang text,
  p_screenshot_urls text[] default '{}',
  p_hp text default ''
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_platform text;
  v_new_count integer;
begin
  if p_hp is not null and p_hp <> '' then
    return;
  end if;

  v_platform := normalize_platform(p_platform);

  update incidents
    set report_count     = report_count + 1,
        last_reported_at = now(),
        quote            = case
          when p_quote is not null and length(trim(p_quote)) > length(trim(quote))
            then p_quote
          else quote
        end,
        artist           = coalesce(nullif(trim(p_artist), ''), artist),
        report_type      = coalesce(nullif(trim(p_report_type), ''), report_type),
        title            = coalesce(nullif(trim(p_title), ''), title),
        platform         = v_platform,
        post_author      = coalesce(nullif(trim(p_post_author), ''), post_author),
        post_date        = coalesce(p_post_date, post_date),
        screenshot_date  = coalesce(p_screenshot_date, screenshot_date),
        screenshot_urls  = case
          when p_screenshot_urls is not null and array_length(p_screenshot_urls, 1) > 0
            then screenshot_urls || p_screenshot_urls
          else screenshot_urls
        end
    where url = p_url
    returning id, report_count into v_id, v_new_count;

  if found then
    insert into incident_events (incident_id, event_type, payload, actor)
    values (
      v_id,
      're_report',
      jsonb_build_object('report_count', v_new_count),
      'reporter'
    );
    return;
  end if;

  insert into incidents (
    artist, report_type, title, quote, platform,
    post_author, post_date, screenshot_date, screenshot_urls,
    url, lang, status, priority, report_count, last_reported_at
  ) values (
    p_artist, p_report_type, p_title, p_quote, v_platform,
    p_post_author, p_post_date, p_screenshot_date,
    coalesce(p_screenshot_urls, '{}'),
    p_url, p_lang, 'new', 'medium', 1, now()
  )
  returning id into v_id;

  insert into incident_events (incident_id, event_type, payload, actor)
  values (
    v_id,
    'submitted',
    jsonb_build_object(
      'report_type', p_report_type,
      'platform', v_platform,
      'artist', p_artist
    ),
    'reporter'
  );
end;
$$;

grant execute on function submit_incident to anon, authenticated;
grant execute on function normalize_platform to anon, authenticated;
