-- Run this in Supabase Dashboard -> SQL Editor
--
-- FRESH INSTALL: run these files in order:
--   1. schema.sql
--   2. migration_v2.sql
--   3. migration_v3.sql
--   4. migration_v4.sql
--
-- EXISTING DATABASE: run only migrations you haven't applied yet (v2 → v3 → v4).
--
-- MIGRATION NOTE: if you already have an "incidents" table from a previous
-- version, run these first:
-- alter table incidents add column if not exists artist text not null default 'Group';
-- alter table incidents add column if not exists screenshot_date date;
-- alter table incidents add column if not exists report_count integer not null default 1;
-- alter table incidents add column if not exists last_reported_at timestamptz not null default now();
-- alter table incidents add column if not exists screenshot_urls text[] not null default '{}';
-- drop policy if exists "Allow all for anon (personal use only)" on incidents;

create table if not exists incidents (
  id bigint generated by default as identity primary key,
  artist text not null default 'Group',
  report_type text not null,
  title text,
  quote text not null,
  platform text not null default 'X (Twitter)',
  post_author text,
  post_date date,
  screenshot_date date,
  screenshot_urls text[] not null default '{}',
  url text not null,
  lang text not null default 'EN',
  status text not null check (status in ('open', 'sent', 'archived')) default 'open',
  report_count integer not null default 1,
  last_reported_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists incidents_url_key on incidents (url);

-- === Row Level Security ===
-- The table itself is locked to authenticated users only (moderators who
-- have logged in via Supabase Auth). The public fandom-facing form never
-- talks to the table directly — it calls the submit_incident() function
-- below, which runs with elevated privileges (security definer) and does
-- controlled insert-or-increment + honeypot filtering.

alter table incidents enable row level security;

drop policy if exists "Authenticated can select" on incidents;
create policy "Authenticated can select" on incidents
  for select using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can update" on incidents;
create policy "Authenticated can update" on incidents
  for update using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can delete" on incidents;
create policy "Authenticated can delete" on incidents
  for delete using (auth.role() = 'authenticated');

-- No insert policy for anon/authenticated on the raw table — all inserts
-- must go through submit_incident() below.

-- === Public submission function ===
-- Anyone (anon, i.e. the whole fandom) can call this. It never exposes
-- read access to the table. If the same URL is reported again, it just
-- bumps report_count (and appends any new screenshots) instead of creating
-- a duplicate row.

create or replace function submit_incident(
  p_artist text,
  p_report_type text,
  p_title text,
  p_quote text,
  p_platform text,
  p_post_author text,
  p_post_date date,
  p_screenshot_date date,
  p_url text,
  p_lang text,
  p_screenshot_urls text[] default '{}',
  p_hp text default ''
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Honeypot: if this hidden field got filled in, it was a bot. Silently
  -- do nothing so the bot doesn't learn its submission was rejected.
  if p_hp is not null and p_hp <> '' then
    return;
  end if;

  update incidents
    set report_count = report_count + 1,
        last_reported_at = now(),
        screenshot_urls = case
          when p_screenshot_urls is not null and array_length(p_screenshot_urls, 1) > 0
            then screenshot_urls || p_screenshot_urls
          else screenshot_urls
        end
    where url = p_url;

  if not found then
    insert into incidents (
      artist, report_type, title, quote, platform,
      post_author, post_date, screenshot_date, screenshot_urls, url, lang,
      status, report_count, last_reported_at
    ) values (
      p_artist, p_report_type, p_title, p_quote, p_platform,
      p_post_author, p_post_date, p_screenshot_date, coalesce(p_screenshot_urls, '{}'), p_url, p_lang,
      'open', 1, now()
    );
  end if;
end;
$$;

grant execute on function submit_incident to anon, authenticated;

-- === Storage bucket for screenshots ===
-- Public bucket: anyone with a link can view a screenshot (needed so
-- moderators can open it), but only the upload action is open to everyone.
-- Deleting files is restricted to logged-in moderators.

insert into storage.buckets (id, name, public)
values ('screenshots', 'screenshots', true)
on conflict (id) do nothing;

drop policy if exists "Public can upload screenshots" on storage.objects;
create policy "Public can upload screenshots"
  on storage.objects for insert
  to public
  with check (bucket_id = 'screenshots');

drop policy if exists "Moderators can delete screenshots" on storage.objects;
create policy "Moderators can delete screenshots"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'screenshots');

